python3 configure.py \
 --prob=MultiPhase \
 --nghost=3 \
 -b \
 -fft \
 -cr \
 -hdf5 \
 -h5double \
 -mpi \
 --mpiccmd='/opt/usr/local/bin/mpicxx' \
 --include='/opt/usr/local' \
 --cflag='-DH5_HAVE_PARALLEL'
